# abstract: this file does the following:
# - defines a display sequence of 3 displays: solid color -> pulse color 1 -> pulse color 2 -> pulse color 1 (looping between the last 2)

# required, must reference a display added below
startup-display = "Solid"
# optional, defaults to false
# verbose = true
# optional, defaults to [], this way you can restrict the program to only connect to a specific serial, in case you have multiple ones.
#                       IF YOU HAVE MULTIPLE DEVICES FEEL FREE TO CONTACT ME! (I cannot test this myself) https://github.com/MuffinMario/quadcast2Srgb
# allowed-serials = ["12345678", "87654321"]

[[display]]
# required
type = "solid"
name = "Solid"
end-condition = { type = "time", duration-ms = 5000 } # optional, if not given display will repeat endlessly
next-display = "Pulse1" # optional, defaults to empty, meaning this display will be the end of the sequence
# end-condition = { type = "time", duration-ms = 5000 } # optional, if not given display will repeat endlessly
# optional, defaults to "#290066" the hash is optional, only here for vscode color picker
# color = "#290066ff" # since vscode color picker adds alpha, it can be included. however it is just ignored.

#[[display]]
# required
#type = "video"
#name = "Video"
#video-path = "/path/to/video.rgb"
# optional, defaults to empty, meaning this display will loop repeat endlessly. video displays also support video-end, as seen below
#end-condition = { type = "video-end" }
#next-display = "Pulse1"
# optional, defaults to 30
# video-framerate = 30
# optional, defaults to "rgb", currently only supports "rgb" and "greyscale", 8 bit each
# video-colors = "rgb"

[[display]]
type = "pulse-color"
name = "Pulse1"
next-display = "Pulse2"
# optional, but you probably want to customize this.
# color = "#290066"
end-condition = { type = "time", duration-ms = 4050 } # optional, if not given display will repeat endlessly
# optional, for custom values check out a generator, e.g. https://cubic-bezier.com
# cubic-bezier = [0.25, 0.1, 0.25, 1.0] # defaults to custom ease in out
# pulse speed is basically the step progress from 0 to 1 in 50ms intervals, meaning we have 20 steps per second
# pulse-speed = 0.025 # optional, defaults to 0.025, bigger number => faster progression.


[[display]]
type = "pulse-color"
name = "Pulse2"
next-display = "Pulse1"
# optional, but you probably want to customize this.
color = "#861e27ff"
end-condition = { type = "time", duration-ms = 2050 } # optional, if not given display will repeat endlessly
cubic-bezier = [0.25, 0.1, 0.25, 1.0]
pulse-speed = 0.05
